POST  http://192.168.1.112/cam HTTP/1.1
content-type: application/json

{
    "count": 2,
    "format": "JPEG",
    "test": 0,
    "testNum": 200,
    "size": "VGA",
    "hz": 24000000,
    "handler": "jpeg",
    "focus": "0"
}