
name: build
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    -  '.github/**'
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.5
      with:
        submodules: 'recursive'
    - uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.1.4
        target: esp32s3

