
name: build
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    -  '.github/**'
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.5
      with:
        submodules: 'recursive'
    - uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.1.4
        target: esp32s3

    - name: upload firemare
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/Kurisu.bin
        retention-days: 90
        compression-level: 0

    # - name: Upload file to bucket
    #   uses: zdurham/s3-upload-github-action@master
    #   with:
    #     args: --acl public-read
    #   env:
    #     FILE: build/Kurisu.bin
    #     S3_ENDPOINT: ${{secrets.S3_ENDPOINT}}
    #     S3_BUCKET: ${{ secrets.S3_BUCKET }}
    #     S3_KEY: Kurisu.bin
    #     AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}       
    #     AWS_REGION: ${{ secrets.S3_REGION }}  
    
    - run: |
          echo "path=$(pwd)" >> $GITHUB_ENV
          ls -la
          
    - run: |
          mkdir -p ota
          ls -la
          cp build/Kurisu.bin /ota/
          
    - uses: jakejarvis/s3-sync-action@master
      # with:
      #   args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.S3_REGION }}   # optional: defaults to us-east-1
        SOURCE_DIR: ota
