
name: build
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    -  '.github/**'
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.5
      with:
        submodules: 'recursive'
    - uses: espressif/esp-idf-ci-action@v1.1.0
      with:
        esp_idf_version: v5.1.4
        target: esp32s3

    - name: upload firemare
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/Kurisu.bin
        retention-days: 90
        compression-level: 0

    - name: Upload file to bucket
      uses: koraykoska/s3-upload-github-action@master
      env:
        FILE: build/Kurisu.bin
        S3_ENDPOINT: '${{secrets.S3_ENDPOINT}}'
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}       
